name: A workflow for my Global World Population App

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'

      - name: Run Unit Tests with Coverage
        run: mvn clean test -Dtest=com.napier.sem.MySQL_Test_Unit_Test

      - name: Upload Unit Test Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./target/site/jacoco/jacoco.xml
          flags: UnitTests
          verbose: true

  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'

      - name: Run Integration Tests with Docker
        run: |
          docker compose up -d db
          mvn test -Dtest=com.napier.sem.MySQL_Test_Integration_Test
          docker compose down

      - name: Upload Integration Test Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./target/site/jacoco/jacoco.xml
          flags: IntegrationTests
          verbose: true

  Build:
    name: Build, Run in Docker and Deploy Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'

      - name: Build and Run Application
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit